version: '3.8'

services:
  web:
    build: .
    container_name: fse4ai-image-classifier
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
