name: Build & Test Python AI Project

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install project (build with pyproject.toml)
      run: pip install . --extra-index-url https://download.pytorch.org/whl/cpu

    # Optionally, run tests if you have:
    - name: Run tests
      run: pytest || true

