name: Build & Test Python AI Project

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install project (build with pyproject.toml)
      run: pip install .

    - name: Run tests
      run: pytest || true
      # Only if you have tests set up. Otherwise, you can remove or comment out this line.

      #workflow
      #Start automatically on pushes and pull requests
      #Install Python 3.9
      #Use pyproject.toml with pip install . to handle installation
      #Run any tests using pytest (if repo includes them)